CREATE OR REPLACE FUNCTION FUN_INSCOR(VID NUMBER, VNOME VARCHAR2)
RETURN NUMBER
IS
QTDID NUMBER(1);
QTDNOME NUMBER(1);

BEGIN
  SELECT COUNT(*) INTO QTDID FROM COR WHERE ID = VID;
  SELECT COUNT(*) INTO QTDNOME FROM COR
                  WHERE UPPER(NOME) = UPPER(VNOME);
  IF QTDID = 0 AND QTDNOME = 0  THEN
  INSERT INTO COR (ID, NOME)  VALUES (VID, VNOME);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Gravou: ' || VNOME);
  RETURN 0;
ELSE
  RETURN 1;
END IF;
END;