DECLARE
  NOME EMPLOYEES.FIRST_NAME%TYPE;
  DEPARTAMENTO DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
  SELECT FIRST_NAME,
    DEPARTMENT_NAME
  INTO NOME,
    DEPARTAMENTO
  FROM EMPLOYEES EMP
  INNER JOIN DEPARTMENTS DEPT
  ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
  WHERE EMPLOYEE_ID    = 100;
  INSERT
  INTO LISTFUNCDEPT
    (
      ID,
      NOME,
      DEPARTAMENTO,
      DATA_HORA
    )
    VALUES
    (
      SEQ_LFD.NEXTVAL,
      NOME,
      DEPARTAMENTO,
      SYSDATE
    );
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('O  resultado é  = ' || NOME || ' - ' || DEPARTAMENTO);
END;