CREATE OR REPLACE PROC_INSCOR(VID NUMBER, VNOME VARCHAR2)
IS
QTDID NUMBER(1);
QTDNOME NUMBER(1);

BEGIN
  SELECT COUNT(*) INTO QTDID FROM COR WHERE ID = VID;
  SELECT COUNT(*) INTO QTDNOME FROM COR
                  WHERE UPPER(NOME) = UPPER(VNOME);
  IF QTDID = 0 AND QTDNOME = 0  THEN
  INSERT INTO COR (ID, NOME)  VALUES (VID, VNOME);
  COMMIT;
  dbms_output.put_line('Gravou: ' || VNOME);
  END IF;
END;