DECLARE
VMENSALIDADE ALUNO.MENS%TYPE
VRA NUMBER;
BEGIN
VRA := 1005;
SELECT MENS INTO VMENSALIDADE
FROM ALUNO
WHERE RA = VRA
IF VMENSALIDADE > 1000 THEN
 INSERT INTO ALUNO (RA, MENS) VALUE (VRA, VMENSALIDADE)
 ELSE
 END IF
END;
